### ISSUE TITLE
Auto assign new report to the user that creates it.

### ISSUE THREAD

**Issue by corsacca** [DiscipleTools/disciple-tools-survey-collection#14]
when creating from the D.T UI, not from the magic link.

**Comment by corsacca** [comment]
@kodinkat can you check if this is already done? If not then do it :)

**Comment by kodinkat** [comment]
> @kodinkat can you check if this is already done? If not then do it :)

@corsacca logic already in.. ;)

![Screenshot 2023-01-23 at 09 49 20](https://user-images.githubusercontent.com/19330800/214010224-09398e9d-3a35-4a9f-8118-de66ad2fed06.png)

**Comment by kodinkat** [comment]
> when creating from the D.T UI, not from the magic link.

@corsacca maybe I should read all comments/requirements first! :wink: Ok, so I don't think this path-way has been covered! On the todo list!
