### ISSUE TITLE
reports dashboard tile metrics not correct

### ISSUE THREAD

**Issue by squigglybob** [DiscipleTools/disciple-tools-survey-collection#16]
the numbers in the reports dashboard tile don't match reality

**Comment by kodinkat** [comment]
Following further investigation, I can confirm the following dashboard metrics reflect report values from records currently assigned to user:

- Total New Baptisms
- Total New Groups
- Total Shares
- Total Prayers
- Total Invites

The following metric however, is sourced from the report record with the most recent **Submission Date**; currently assigned to user:

- Current Active Groups

Therefore, which metric is currently incorrect?

![Screenshot 2023-01-05 at 11 59 27](https://user-images.githubusercontent.com/19330800/210775954-63dbfef6-5647-4246-81a6-fc85cd2d4e42.png)

**Comment by squigglybob** [comment]
Yeah, The maths is working out for me too.
Maybe as you said Andrew was using different links each time.
Or maybe he was expecting the current active groups to also be a total of all time.

**Comment by squigglybob** [comment]
As per testing "incorrect" metrics on the dynamic extra fields ticket #29 

IF a submission date is in the future
THEN it won't be counted in the metrics

To fix this, we could give a warning next to the input to alert the user if they select a submission date that is in the future

Similarly if the report start date is after the submission date, this could also raise an error by the input
