### ISSUE TITLE
dashboard plugin requested to be installed even though it has already been installed

### ISSUE THREAD

**Issue by squigglybob** [DiscipleTools/disciple-tools-survey-collection#18]
If you install the dashboard plugin from the extensions tab you still get a notice to install the required plugin at the top.

If you try to activate it from the message button it fails as it's already installed.

**Comment by squigglybob** [comment]
Minor bug: I think that the backend extension is saying that the old version of the dashboard plug-in needs to be installed when the new version is already installed and working properly.

Weird error: There's a plug-in that's failing to activate, but it doesn't appear to be significant for our use case. It's the plug-in, "Disciple.Tools - Dashboard." When we try to Activate it, we get an error code: "Plugin could not be activated because it triggered a fatal error. Fatal error: Cannot redeclare dt_dashboard_plugin_hook_admin_notice() (previously declared in /nas/content/live/teamexglobal/wp-content/plugins/disciple-tools-dashboard-plugin/disciple-tools-dashboard.php:345) in /nas/content/live/teamexglobal/wp-content/plugins/disciple-tools-dashboard/disciple-tools-dashboard.php on line 344

It looks like the plugin is installed twice…
Confusing, but nothing critical - can ignore, but need to clean up eventually - low priority.

**Comment by corsacca** [comment]
This is an issue with the tgm implementation when the plugin has already been installed with a different folder name.
