### ISSUE TITLE
reports dashboard tile - hard code new metrics

### ISSUE THREAD

**Issue by squigglybob** [DiscipleTools/disciple-tools-survey-collection#19]
This would be a quick fix to get some new metrics that they want to be displayed in the reports dashboard tile.

**Comment by squigglybob** [comment]
Issue: Dashboard tile and metrics page {Survey Collection Metrics - Report Statistics] neither one show group total participants or new fields added to the tracking tile (Accountability or Number Trained).
Similarly: Re-order of Dashboard tile and metrics page to show different order of stats - prioritizing lead metrics (ideally reflecting the "tracking tile" of the reports.
Quick fix would be to hard code add the three new fields and change the hardcoded order.

**Comment by corsacca** [comment]
Already implement and/or not going for hard coded
