### ISSUE TITLE
reports not showing up straight away in magic link

### ISSUE THREAD

**Issue by squigglybob** [DiscipleTools/disciple-tools-survey-collection#21]
When reporting in the magic link:

It should show the last 5 reports that are made.

After creating a few reports it can take up to an hour for the reports to show in the list of the last 5 in the magic link.

You would expect the reports to show up in that list straight away

Could this be to do with the cronjob or something?

**Comment by corsacca** [comment]
This would be a caching issue

**Comment by corsacca** [comment]
Confirmed.
![image](https://user-images.githubusercontent.com/24901539/213441083-b45f266c-2a47-4829-b188-04c58d97c24b.png)

**Comment by corsacca** [comment]
Possible solution: https://github.com/DiscipleTools/disciple-tools-bulk-magic-link-sender/commit/cdf0d2a1d7fa1c3347601354b091c340059d0efa
https://github.com/DiscipleTools/disciple-tools-theme/commit/18a347297d95f15a8b7625ff1ebf471463073d0c was supposed to address this issue.

**Comment by corsacca** [comment]
Fixed by https://github.com/DiscipleTools/disciple-tools-survey-collection/commit/88d84796ddd273916956859c4603c93dae2ce084
