### ISSUE TITLE
issue with the report name

### ISSUE THREAD

**Issue by squigglybob** [DiscipleTools/disciple-tools-survey-collection#22]
Some people are getting an error of an invalid report name.

Currently the name is the same as the contents of the submission date field.

It could be related to some people getting errors with the submission date if they don't click 'apply' on the date selector but click off it instead

To fix this we could either allow the user to set the name of the report, 

Or just use today as the submission date, and programmatically create the name of the report.

**Comment by squigglybob** [comment]
Bug: Error: “Please ensure a valid report name is specified” - Report submission requires valid date selection to make a valid report name.  You can type the date or select the date and tab away without hitting "apply" and it will not set the date and trigger the report name.

If it's not going to cause any problems, I would humbly suggest that, if the "report name" section of the code is going to be that picky, but not give the user any feedback about why the report name is not valid, then just use a system value (like the system date/time) for the name of the report.

I’ve selected date without hitting apply in Safari and Chrome and it is still working - might be edge or typed
I think that they should be able to name the report - let the date selection fill in a blank report title, but the title can be named manually.

**Comment by corsacca** [comment]
Fixed in https://github.com/DiscipleTools/disciple-tools-survey-collection/commit/de14db1624a85695efa1b2b81ff9028dd739cc81
