### ISSUE TITLE
can't filter by assigned to field correctly in reports post type

### ISSUE THREAD

**Issue by squigglybob** [DiscipleTools/disciple-tools-survey-collection#23]
Create a new filter.
try to select an assigned to user.
The field will not show any users and looks/feels like a text field.

'assigned to me' quick filter shows incorrect number of records

This could be linked to #16 if the assigned to field is not working correctly then the metrics would not be able to be gathered correctly either

**Comment by squigglybob** [comment]
clicking assigned to me filter, does however show the correct number of records that are assigned to me, so it's partly working partly not

**Comment by corsacca** [comment]
Assigned to me number is wrong, shows "all" instead of the number assigned to me.

![Image](https://user-images.githubusercontent.com/24901539/214007939-1c91a8e3-3776-4940-ac55-644eaf81d480.png)

**Comment by corsacca** [comment]
Assigned to filter won't populate with users. See error in console.


![Image](https://user-images.githubusercontent.com/24901539/214008400-4cda23eb-61f7-42f0-8566-bd3c44bf1c32.png)
