### ISSUE TITLE
hardcode new metrics in the dashboard tile

### ISSUE THREAD

**Issue by squigglybob** [DiscipleTools/disciple-tools-survey-collection#29]
order and metrics the same as the data collected in the reports form

they want the metrics in the dashboard tile to reflect the metrics order and total from the form.

The new fields in the reports form are

with the same name in lower case as the name of the field in the image

![Image](https://user-images.githubusercontent.com/9816214/210772393-f9235b6f-c958-414b-88f3-5974b1090bf4.png)

They wouldn't need the accountability date to be in the metrics for Sunday, but a future issue/feature request, would be to have a count of days since the last accountability date, in the list of metrics see #31 unless it's easy to roll that metric into this issue

**Comment by kodinkat** [comment]
Logic has now been updated to dynamically detect and generate new dashboard metrics for fields of type `number` and added to `tracking` tile. See attached screenshots below:

![Screenshot 2023-01-06 at 10 42 48](https://user-images.githubusercontent.com/19330800/210998321-b65d6039-5b17-4fff-ac8a-d5d52448848f.png)

![Screenshot 2023-01-06 at 10 43 14](https://user-images.githubusercontent.com/19330800/210998328-c56e0e99-2205-4586-aabf-b8e551c1a256.png)

![Screenshot 2023-01-06 at 10 43 37](https://user-images.githubusercontent.com/19330800/210998331-fe92a913-2225-4530-ac12-5396f0d9394f.png)
