### ISSUE TITLE
dashboard metric for days since last reported accountability

### ISSUE THREAD

**Issue by squigglybob** [DiscipleTools/disciple-tools-survey-collection#31]
This would be a personal metric for the reporter.

It would give them the number of days since their last reported accontability meeting from their reports.

The idea would be that this would give them some accountability for making sure that it's not been too long between accountability meetings

**Comment by corsacca** [comment]
Is this a "X days since last report" in this tile?

![Image](https://user-images.githubusercontent.com/24901539/219023147-b38e10d2-f88d-4271-b7f8-8a7bec6e7a66.png)
