### ISSUE TITLE
participants metric to only show last submitted report numbers

### ISSUE THREAD

**Issue by squigglybob** [DiscipleTools/disciple-tools-survey-collection#34]
This is to function in the same way as the active groups metric.

On the global metrics it would therefore also be summing up all of the last submitted reports for the global stats, so that participants and active groups work in the same way everywhere

**Comment by corsacca** [comment]
On global metrics
Sum up the participants for all the users
![image](https://user-images.githubusercontent.com/24901539/214548095-b128876e-ce91-4037-993e-9d4a141f7745.png)
