### ISSUE TITLE
Global active groups metric incorrect

### ISSUE THREAD

**Issue by squigglybob** [DiscipleTools/disciple-tools-survey-collection#35]
![image](https://user-images.githubusercontent.com/9816214/211328874-d315e473-6d6b-4e7c-8b73-66511d03b99f.png)

Shows the global active groups to be zero, but on looking at the reports list an a site with live data, the total for this should be well over 100.

It should be showing the total active groups for all of the last submitted reports of everybody on the system.

**Comment by kodinkat** [comment]
@squigglybob 

I've now revisited logic; which appears to be working as initially intended - Active Groups stats calculated as follows:

- User Report Statistics:
  - The most recent report record for current user, is identified, based on most recent `submit_date`.
  - Once identified, the `Current Active Groups` value is used.
    - Therefore, if it's zero (0); then this will be shown.


- Global Report Statistics:
  - The most recent report records across all users, are identified, based on most recent `submit_date`.
  - Once identified, the `Current Active Groups` value across all records are summed and returned.

Therefore, quick sanity check - all last submitted reports contain valid active group values?
